// Import the createSlice function from @reduxjs/toolkit
import { createSlice } from "@reduxjs/toolkit";

// Define a slice of state called 'counterSlice'
const counterSlice = createSlice({
  // Name of the slice
  name: "counter",
  
  // Initial state of the slice, with a single property 'value' set to 0
  initialState: { value: 0 },

  // Reducers are functions that define how the state can be updated
  reducers: {
    // Reducer to increment the 'value' in the state
    increament: (state) => {
      // Increment the 'value' property in the state
      ++state.value;
    },
    // Reducer to decrement the 'value' in the state
    decreament: (state) => {
      // Decrement the 'value' property in the state
      --state.value;
    },
  },
});

// Export the actions generated by createSlice, so they can be used in components
export const { increament, decreament } = counterSlice.actions;

// Export the reducer function to be used in the store configuration
export default counterSlice.reducer;

